### ISSUE TITLE
Brave Panel UI ToDo items

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#265]
- [ ]  add favicon to url
- [x]  add section titles <br>Not sure how to fit this on iphone 5 screen
- [x]  vert align titles on last 2 sections<br>Bump the stats section titles right by 15 px <br>Not sure will fit on iPhone 4s screen

**Comment by garvankeeley** [comment]
@bradleyrichter adding designs
![pasted_image_at_2016_06_23_01_55_pm_720](https://cloud.githubusercontent.com/assets/5495083/16319989/8d0461ba-3963-11e6-8fe4-e76584a5462b.png)

**Comment by garvankeeley** [comment]
iPhone screens 568px and less will get one section title, larger ones will get both.

Favicon is delayed to later release, I'm concerned with the current favicon provider code, still seeing bugs in favicons not loading when they should, would rather not make the bug more obvious until that code is improved. Handling blank favicons is an issue regardless. If we move the title, we can have the title snapping right once the favicon loads. If we don't move the title, we have a blank space where there is no favicon.

**Comment by garvankeeley** [comment]
Update design doc for iPhone 5 screen
![pasted image at 2016_06_27 11_33 am](https://cloud.githubusercontent.com/assets/5495083/16391334/a6039d98-3c74-11e6-8c08-8ee596eeb581.png)
