### ISSUE TITLE
Edit Bookmark meta bug

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#394]
- [x] Edit Dialog too low in z-order (see screenshot)
- [x] Edit Dialog not centered after device rotation on iPhone
- [x] iPad: edit dialog anchored to left edge of edit button, seems like a wierd spot 
- [x] Labels too close to left edge (see screenshot)
- [X] <del>Bookmarks stays in edit mode after closing panel if swipe to edit was used, STR: swipe to expose edit button, press edit, tap on webview so that panel closes, re-open panel</del> (See #404)
- [x] Editing Title: Can't press return to close keyboard
- [x] Editing Title on iPhone: crash in force cast `func currentBookmarksPanel() -> BookmarksPanel {
        return self.navigationController?.visibleViewController as! BookmarksPanel
    }  `
 
stack trace 
```
BookmarksPanel.currentBookmarksPanel() -> BookmarksPanel at /Client/Frontend/Home/BookmarksPanel.swift:704
 MainSidePanelViewController.willHide() -> () at /brave/src/frontend/sidepanels/MainSidePanelViewController.swift:95
BraveTopViewController.dismissAllSidePanels() -> () at /brave/src/frontend/BraveTopViewController.swift:74
```

<img width="377" alt="screenshot 2016-09-02 13 33 52" src="https://cloud.githubusercontent.com/assets/5495083/18212628/40abe8ce-7112-11e6-9bdd-d0f80bbf0ae1.png">

**Comment by diegodoval** [comment]
should be fixed with latest changes pushed to PR https://github.com/brave/browser-ios/pull/413

**Comment by diegodoval** [comment]
fixed in PR #413
