### ISSUE TITLE
Manual tests for iPhone5 (iOS9) 1.2.16 beta1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#430]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check the Brave version in About and make sure it is EXACTLY as expected.

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## Bookmarks

1. [x] Test that creating a bookmark in the left well works
2. [x] Test that clicking a bookmark in the left well loads the bookmark.
3. [x] Test that deleting a bookmark in the left well works

## Context menus

1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).
5. [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

1. [x] Ensure search box is shown when selected via the share menu
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results

## Private Mode

1. [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## History

1. [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
2. [x] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test that you can save an image from a site.

## Fullscreen

1. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Gestures

1. [x] Test zoom in / out gestures work
2. [x] Test that navigating to a different origin resets the zoom
3. [x] Swipe back and forward to navigate, verify this works as expected

## Bravery settings

1. [x] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [x] Check that ad replacement works on http://slashdot.org
4. [x] Check that toggling to blocking and allow ads works as expected.
5. [x] Test that clicking through a cert error in https://badssl.com/ works.
6. [x] Test that Safe Browsing works (http://excellentmovies.net/)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for http://excellentmovies.net/.
8. [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [x] Test that preferences default Bravery settings take effect on pages with no site settings.
10. [x] Test that turning on fingerprinting protection in preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [x] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked.
12. [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [x] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [x] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`.
5. [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
6. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
7. [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).
8. [x] Test that news.google.com sites open in a new tab (due to target being _blank).

## Top sites view

1. [x] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

1. [x] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

## Per release specialty tests

- [x] Top Sites: show better default set and require more site visits to bump the defaults off ([#423](https://github.com/brave/browser-ios/issues/423))
- [x] Find-in-page crashes or very slow on large sites ([#421](https://github.com/brave/browser-ios/issues/421))
- [x] Save and auto-fill passwords not triggering reliably ([#398](https://github.com/brave/browser-ios/issues/398))
- [x] m.jpost.com doesn't load with adblock+tp on ([#385](https://github.com/brave/browser-ios/issues/385))
- [x] App handlers are re-triggered on launch. ([#382](https://github.com/brave/browser-ios/issues/382))
- [x] add New Tab button to tabs bar ([#295](https://github.com/brave/browser-ios/issues/295))
- [x] The first letter is duplicated in URL bar in non-alphabet language ([#415](https://github.com/brave/browser-ios/issues/415))
- [x] Edit Bookmark meta bug ([#394](https://github.com/brave/browser-ios/issues/394))
- [x] Bookmarks Edit mode: Titles overlapping right accessory icon ([#384](https://github.com/brave/browser-ios/issues/384))
- [x] After clearing private data, the intro screen shows, and keeps popping up ([#424](https://github.com/brave/browser-ios/issues/424))
- [ ] Tab overview shows the shows the first tab page preview on the last tab ([#419](https://github.com/brave/browser-ios/issues/419))
- [x] After deleting private data, the history table is not refreshed ([#416](https://github.com/brave/browser-ios/issues/416))
- [x] Can't scroll to see content at very bottom ([#393](https://github.com/brave/browser-ios/issues/393))
- [x] Can't click link if at the bottom of a page ([#414](https://github.com/brave/browser-ios/issues/414))
- [x] Individual Controls reset ([#395](https://github.com/brave/browser-ios/issues/395))
- [x] context-menu delay: match Safari at 850ms (not 500ms as is now) ([#407](https://github.com/brave/browser-ios/issues/407))
- [x] Bookmarks stays in edit mode after closing panel if swipe to edit was used ([#404](https://github.com/brave/browser-ios/issues/404))
- [x] When shields are down, the individual controls should mirror the down status. ([#374](https://github.com/brave/browser-ios/issues/374))

## Session storage

1. [x] Test that tabs restore when closed, including active tab.

**Comment by garvankeeley** [comment]
- `Downloads: Test downloading a file works and that all actions on the download item works.` iOS app won't handle downloads (edited)

- `Fullscreen: Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)`
You mean full-screen video I assume? I added the word video (edited)

- The zoom section: FYI, that is handled by the UIWebView, we have no code or control over that.

- `Test that about:preferences default Bravery settings take effect on pages with no site settings.`
No about:prefs, but I know what you mean there

- Add a section for testing _blank targets: news.google.com articles should  open in new tab

**Comment by garvankeeley** [comment]
`Content tests` section, some is pure UIWebView internals, thus not handled by us, might be ok to test, but the low-priority items are:
- Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
- Load twitter and click on a tweet so the popup div shows. Click to dismiss and repeat with another div. Make sure it shows.

These can go:
- `Open a github issue and type some misspellings, make sure they are underlined.`
- `Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.`
- `Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it. Click on it and make sure it is already loaded.
`

**Comment by garvankeeley** [comment]
This lost some tests from the previous template, such as the private browsing tests, which are high priority.

**Comment by garvankeeley** [comment]
Here are items from previous we should retain: 
`In Settings: Verify changing the default search engine
`Private Mode
 Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list`

`History on pages using history-push
 On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.`
 Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.
Web view`

` Context menu: verify you can Open in Background Tab, and Open in Private Tab`
` Swipe back and forward to navigate, verify this works as expected`

**Comment by garvankeeley** [comment]
The bug links are all linking to laptop BTW

**Comment by alexwykoff** [comment]
Much obliged for the feedback, I'm adding these changes to the wiki page : https://github.com/brave/browser-ios/wiki/Manual-Tests and to the individual issues.

**Comment by alexwykoff** [comment]
lgtm
