### ISSUE TITLE
Manual tests for iPad Air(iOS9) 1.2.16 beta 1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#431]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check the Brave version in About and make sure it is EXACTLY as expected.

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## Bookmarks

1. [x] Test that creating a bookmark in the left well works
2. [x] Test that clicking a bookmark in the left well loads the bookmark.
3. [x] Test that deleting a bookmark in the left well works

## Context menus

1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).
5. [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

1. [x] Ensure search box is shown when selected via the share menu
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results

## Private Mode

1. [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## History

1. [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
2. [x] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test that you can save an image from a site.

## Fullscreen

1. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Gestures

1. [x] Test zoom in / out gestures work
2. [x] Test that navigating to a different origin resets the zoom
3. [ ] Swipe back and forward to navigate, verify this works as expected

## Bravery settings

1. [x] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [x] Check that ad replacement works on http://slashdot.org
4. [x] Check that toggling to blocking and allow ads works as expected.
5. [x] Test that clicking through a cert error in https://badssl.com/ works.
6. [x] Test that Safe Browsing works (http://excellentmovies.net/)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for http://excellentmovies.net/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`.
5. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
6. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
7. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).
8. [ ] Test that news.google.com sites open in a new tab (due to target being _blank).

## Top sites view

1. [ ] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

1. [ ] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

## Per release specialty tests

- [ ] Top Sites: show better default set and require more site visits to bump the defaults off ([#423](https://github.com/brave/browser-ios/issues/423))
- [ ] Find-in-page crashes or very slow on large sites ([#421](https://github.com/brave/browser-ios/issues/421))
- [ ] Save and auto-fill passwords not triggering reliably ([#398](https://github.com/brave/browser-ios/issues/398))
- [ ] m.jpost.com doesn't load with adblock+tp on ([#385](https://github.com/brave/browser-ios/issues/385))
- [ ] App handlers are re-triggered on launch. ([#382](https://github.com/brave/browser-ios/issues/382))
- [ ] add New Tab button to tabs bar ([#295](https://github.com/brave/browser-ios/issues/295))
- [ ] The first letter is duplicated in URL bar in non-alphabet language ([#415](https://github.com/brave/browser-ios/issues/415))
- [ ] Edit Bookmark meta bug ([#394](https://github.com/brave/browser-ios/issues/394))
- [ ] Bookmarks Edit mode: Titles overlapping right accessory icon ([#384](https://github.com/brave/browser-ios/issues/384))
- [ ] After clearing private data, the intro screen shows, and keeps popping up ([#424](https://github.com/brave/browser-ios/issues/424))
- [ ] Tab overview shows the shows the first tab page preview on the last tab ([#419](https://github.com/brave/browser-ios/issues/419))
- [ ] After deleting private data, the history table is not refreshed ([#416](https://github.com/brave/browser-ios/issues/416))
- [ ] Can't scroll to see content at very bottom ([#393](https://github.com/brave/browser-ios/issues/393))
- [ ] Can't click link if at the bottom of a page ([#414](https://github.com/brave/browser-ios/issues/414))
- [ ] Individual Controls reset ([#395](https://github.com/brave/browser-ios/issues/395))
- [ ] context-menu delay: match Safari at 850ms (not 500ms as is now) ([#407](https://github.com/brave/browser-ios/issues/407))
- [ ] Bookmarks stays in edit mode after closing panel if swipe to edit was used ([#404](https://github.com/brave/browser-ios/issues/404))
- [ ] When shields are down, the individual controls should mirror the down status. ([#374](https://github.com/brave/browser-ios/issues/374))

## Session storage

1. [ ] Test that tabs restore when closed, including active tab.
