### ISSUE TITLE
Manual tests for iPhone 6 (iOS10) 1.2.19 RC1

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#612]
## Pre-release check list
1. [x] Killing the app clears the stats counter ([#634](https://github.com/brave/browser-ios/issues/634))
2. [ ] Buggy transition to top sites screen (stats show then hide, fonts change for final layout) ([#627](https://github.com/brave/browser-ios/issues/627))
3. [ ] Empty div shown on Facebook chat when keyboard pops out  ([#548](https://github.com/brave/browser-ios/issues/548))
4. [x] Reader mode settings are not saved between swipe back/forward ([#623](https://github.com/brave/browser-ios/issues/623))
5. [x] Newtab flashes before loading a webpage ([#622](https://github.com/brave/browser-ios/issues/622))
6. [x] Stat count automatically increases after restarting the app ([#624](https://github.com/brave/browser-ios/issues/624)) 
7. [x] Global stats: split up TP and AB to match desktop. ([#621](https://github.com/brave/browser-ios/issues/621))
8. [x] [beta] reader mode shields showing url as 'localhost' ([#620](https://github.com/brave/browser-ios/issues/620))
9. [x] Add newtab page stats like desktop has enhancement ([#588](https://github.com/brave/browser-ios/issues/588))
10. [x] Improve private mode stat styling ([#619](https://github.com/brave/browser-ios/issues/619))
11. [x] Swipe back doesn't go back to article from reader mode ([#616](https://github.com/brave/browser-ios/issues/616))
12. [x] Ads Tracker count doesn't stop on https://www.yahoo.com ([#618](https://github.com/brave/browser-ios/issues/618))
13. [x] Opening a link from reader mode and closing it doesn't load the reader mode again ([#615](https://github.com/brave/browser-ios/issues/615))
14. [x] Bottom tool bar moves up to mid screen when scrolling (needs STR) more info needed ([#351](https://github.com/brave/browser-ios/issues/251))
15. [x] Email/Confirm Email field hidden by keyboard on ebay.com web compat ([#539](https://github.com/brave/browser-ios/issues/539))
16. [x] [Beta] deadlock when tab overview is selected ([#608](https://github.com/brave/browser-ios/issues/608))
17. [x] Local Storage and Private Mode issue ([#606](https://github.com/brave/browser-ios/issues/606))
18. [x] Add Reader mode browser parity enhancement ([#3](https://github.com/brave/browser-ios/issues/3))
19. [x] Shields icon is not disabled on a new tab suggestion ([#496](https://github.com/brave/browser-ios/issues/496))
20. [x] Fresh tab: add overview text area to brave panel when disabled ([#277](https://github.com/brave/browser-ios/issues/277))
21. [x] added shields overview to brave panel when disabled ([#599](https://github.com/brave/browser-ios/issues/599))
23. [x] Reader mode icon shows then hides during page load ([#596](https://github.com/brave/browser-ios/issues/596))
24. [x] Brave crashes when print cancelled after searching for printers crash ([#579](https://github.com/brave/browser-ios/issues/579))
25. [x] Site FavIcon is not shown on tabs when cycling through opened tabs UX ([#549](https://github.com/brave/browser-ios/issues/549))
26. [ ] If CSP on main doc 'sandbox': No url displayed, brave shields panel won't open ([#592](https://github.com/brave/browser-ios/issues/592))
27. [x] Turning off Shields on a site increases Fingerprint protection blocked counter ([#636](https://github.com/brave/browser-ios/issues/636))

## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check the Brave version in About and make sure it is EXACTLY as expected.

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## Bookmarks

1. [x] Test that creating a bookmark in the left well works
2. [x] Test that clicking a bookmark in the left well loads the bookmark.
3. [x] Test that deleting a bookmark in the left well works

## Context menus

1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).
5. [ ] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

1. [x] Ensure search box is shown when selected via the share menu
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results

## Private Mode

1. [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## History

1. [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
2. [x] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test that you can save an image from a site.

## Fullscreen

1. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Gestures

1. [x] Test zoom in / out gestures work
2. [x] Test that navigating to a different origin resets the zoom
3. [x] Swipe back and forward to navigate, verify this works as expected

## Bravery settings

1. [x] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [x] Check that ad replacement works on http://slashdot.org
4. [x] Check that toggling to blocking and allow ads works as expected.
5. [x] Test that clicking through a cert error in https://badssl.com/ works.
6. [x] Test that Safe Browsing works (http://excellentmovies.net/)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for http://excellentmovies.net/.
8. [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [x] Test that preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked.
12. [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [x] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`.
5. [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
6. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
7. [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).
8. [x] Test that news.google.com sites open in a new tab (due to target being _blank).

## Top sites view

1. [x] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

1. [x] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

## Per release specialty tests

1. [ ] Test each item in release notes for the release that's going out.

## Session storage

1. [x] Test that tabs restore when closed, including active tab.

**Comment by srirambv** [comment]
Looks good. Closing #612
