### ISSUE TITLE
Manual tests for iPhone 6s+ (iOS9) 1.3.2 RC1

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#820]
## Pre-release check list
1. [ ]  New tab switch doesn't happen on 0.13.2  ([#815](https://github.com/brave/browser-ios/issues/815))
2. [x]  In Private Mode URL Bar should use Dark Keyboard  ([#811](https://github.com/brave/browser-ios/issues/811))
3. [x]  History items are listed even with irrelevant character entered in URL bar  ([#809](https://github.com/brave/browser-ios/issues/809))
4. [x]  Search in page option should not be shown on a new tab bug  ([#808 ](https://github.com/brave/browser-ios/issues/808))
5. [x]  Shield stats are not properly shown on sites  ([#807](https://github.com/brave/browser-ios/issues/807))
6. [x]  Editing bookmark should not allow empty URL field  ([#806](https://github.com/brave/browser-ios/issues/806))
7. [x]  Opening a bookmark doesn't show the bookmark indicator(Orange Star)  ([#805](https://github.com/brave/browser-ios/issues/805))
8. [x]  Add Safari-like Find in Page enhancement  ([#804](https://github.com/brave/browser-ios/issues/804))
9. [x]  Allow Folders with Records to be Deleted  ([#800](https://github.com/brave/browser-ios/issues/800))
10. [x]  Always Show "New Folder" Option  ([#798](https://github.com/brave/browser-ios/issues/798))
12. [x]  Have default Favicon Icon  ([#797](https://github.com/brave/browser-ios/issues/797))
12. [x]  Minimize Telemetry Events  ([#795](https://github.com/brave/browser-ios/issues/795))
13. [x]  Support section missing from the new beta build  ([#792](https://github.com/brave/browser-ios/issues/792)) 
~~Tab Restoration Fails  ([#788](https://github.com/brave/browser-ios/issues/788))~~ 
15. [x]  Report a bug opens in normal tab even when private browsing only is enabled  ([#779](https://github.com/brave/browser-ios/issues/779)) 
16. [x]  Folder title is shown only after tapping on Done  ([#778](https://github.com/brave/browser-ios/issues/778)) 
17. [x]  Renaming a bookmark folder behaves like a bookmark  ([#777](https://github.com/brave/browser-ios/issues/777)) 
18. [x]  HTTPSE issue with http://journals.plos.org/  ([#775](https://github.com/brave/browser-ios/issues/775)) 
19. [x]  Tab count has strange animation before loading the tabs  ([#774](https://github.com/brave/browser-ios/issues/774))
20. [x]  Browser crashes when trying to move bookmark from root folder to empty titled bookmark folder  ([#771](https://github.com/brave/browser-ios/issues/771))
21. [x]  Removing bookmark folder name causes it to show as root folder when trying to move a boomark  ([#770](https://github.com/brave/browser-ios/issues/770)) 
22. [x]  Opening a empty title folder shows Bookmarks as the title enhancement  ([#769](https://github.com/brave/browser-ios/issues/769)) 
23. [x]  Unable to delete added bookmark  ([#766](https://github.com/brave/browser-ios/issues/766)) 
24. [ ]  Add Iran add blocking   ([#758](https://github.com/brave/browser-ios/issues/758)) 
25. [x]  Support bitwarden password manager autofill app extension enhancement  ([#743](https://github.com/brave/browser-ios/issues/743))
26. [x]  iTunes app details needs to update support information  ([#742](https://github.com/brave/browser-ios/issues/742))
27. [x]  Scroll gesture can trigger navigation  ([#741](https://github.com/brave/browser-ios/issues/741))
28. [x]  Wrong favicons shown on top site tiles  ([#737](https://github.com/brave/browser-ios/issues/737)) 
29. [x]  Tabs bar covers the top part of webpage  ([#729](https://github.com/brave/browser-ios/issues/729))  
30. [x]  Unable to save Bookmarklet for Unmark bookmark manager (e.g. unable to edit URL on   ([#728](https://github.com/brave/browser-ios/issues/728)) 
31. [x]  Folder names cannot be edited to have space-only titles  ([#705](https://github.com/brave/browser-ios/issues/705)) 
32. [x]  Tab restore bug: current tab not restoring, background tabs seem ok  ([#695](https://github.com/brave/browser-ios/issues/695)) 
33. [x]  Keep bookmark icon color consistent when navigating between settings and webview  ([#688](https://github.com/brave/browser-ios/issues/688)) 
34. [x]  Unable to access current page after not using for a while  ([#644](https://github.com/brave/browser-ios/issues/644)) 
35. [ ]  Buggy transition of newtab on app launch  ([#635](https://github.com/brave/browser-ios/issues/635)) 
36. [ ]  Buggy transition to top sites screen (stats show then hide, fonts change for final layout)  ([#627](https://github.com/brave/browser-ios/issues/627)) 
37. [ ]  [Beta]1Password button shown by default even when 3rd party password manager is set to don't use  ([#535](https://github.com/brave/browser-ios/issues/535)) 
38. [ ]  Top Sites: is based on page visits, not domain visits, see if this can be changed  ([#446](https://github.com/brave/browser-ios/issues/446)) 
39. [ ]  Disabling Private Browsing Only still creates new private tabs enhancement  ([#439](https://github.com/brave/browser-ios/issues/439)) 
40. [ ]  Stay in Private mode, make it a persistent app state enhancement  ([#319](https://github.com/brave/browser-ios/issues/319)) 

## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check the Brave version in About and make sure it is EXACTLY as expected.

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## Bookmarks

1. [x] Test that creating a bookmark in the left well works
2. [x] Test that clicking a bookmark in the left well loads the bookmark
3. [x] Test that deleting a bookmark in the left well works
4. [x] Test that creating a bookmark folder works
5. [ ] Test that creating a bookmark inside the created folder works
6. [ ] Test that you are able to add a bookmark directly inside a bookmark folder
7. [x] Test that you are able to delete a bookmark in edit mode
8. [ ] Test that you are able to delete a bookmark folder with bookmarks inside

## Context menus

1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).
5. [ ] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

1. [ ] Ensure search box is shown when selected via the share menu
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results

## Private Mode

1. [ ] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## Reader Mode
1. [ ] Visit http://m.slashdot.org, open any article, verify the reader mode icon is shown in the URL bar
2. [ ] Verify tapping on the reader mode icon opens the article in reader mode
3. [ ] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## History

1. [ ] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
2. [ ] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test that you can save an image from a site.

## Fullscreen

1. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Gestures

1. [ ] Test zoom in / out gestures work
2. [ ] Test that navigating to a different origin resets the zoom
3. [ ] Swipe back and forward to navigate, verify this works as expected

## Password Managers
1. [ ] Test tapping on 1Password on the silde out keyboard launches 1Password App and able to select the stored credentials 

## Sync
~~Ensure you are able to scan the QR code and sync with laptop~~
~~Ensure the bookmarks from laptop shows up on the mobile after sync completes~~
~~Add a bookmark on mobile and check if it gets synced to the laptop~~

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://zyan.scripts.mit.edu/public
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to http://zyan.scripts.mit.edu/public
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://downloadme.org/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in preferences shows 1 fingerprints blocked at https://browserleaks.com/canvas . Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows
3. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password prompt is shown and saves the password
4. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
5. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
6. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
7. [ ] Test that news.google.com sites open in a new tab (due to target being _blank)

## Top sites view

1. [ ] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

1. [ ] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

## Session storage

1. [ ] Test that tabs restore when closed, including active tab.
